# Generated by Django 2.0.4 on 2018-04-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('cell_phone', models.CharField(blank=True, default='', max_length=15)),
                ('gender', models.NullBooleanField(default=None)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('medical_information', models.CharField(blank=True, default='', max_length=512)),
                ('medical_condition', models.CharField(blank=True, default='', max_length=512)),
                ('invited', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
